name: Validate Integration

on:
  push:
    branches:
      - main
      - dev
  pull_request:
  schedule:
    - cron: "0 0 * * *" # Körs automatiskt varje natt för att upptäcka om HA Core ändrat något

jobs:
  hassfest:
    name: Run Hassfest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Hassfest validation
        uses: home-assistant/actions/hassfest@master

  hacs:
    name: Run HACS Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: HACS validation
        uses: hacs/action@main
        with:
          category: integration
